In [1]:
import torch

In [2]:
v = torch.Tensor([[4,1,3],[1,3,1],[2,0,5]])

In [3]:
a = v.view(3,3)

In [4]:
a

tensor([[4., 1., 3.],
        [1., 3., 1.],
        [2., 0., 5.]])

In [5]:
b = torch.eig(a, True)

In [6]:
b

torch.return_types.eig(
eigenvalues=tensor([[1.8074, 0.0000],
        [7.1926, 0.0000],
        [3.0000, 0.0000]]),
eigenvectors=tensor([[-0.8191,  0.7001, -0.4082],
        [ 0.2566,  0.3193, -0.8165],
        [ 0.5131,  0.6386,  0.4082]]))

In [7]:
c = b.eigenvectors

In [8]:
c

tensor([[-0.8191,  0.7001, -0.4082],
        [ 0.2566,  0.3193, -0.8165],
        [ 0.5131,  0.6386,  0.4082]])

In [9]:
import numpy
d = c.numpy()
e = [i[2] for i in d]
e

[-0.40824845, -0.8164965, 0.4082484]

In [10]:
f = e/max(e)

In [11]:
import numpy as np
g = np.sort([round(i) for i in f])

In [12]:
g

array([-2., -1.,  1.], dtype=float32)