In [1]:
import torch

In [2]:
v = torch.Tensor([[1.,4.,0.,0.],[0.,2.,0.,0.],[5.,3.,1.,1.],[4.,7.,2.,2.]])

In [3]:
a = v.view(4,4)
a

tensor([[1., 4., 0., 0.],
        [0., 2., 0., 0.],
        [5., 3., 1., 1.],
        [4., 7., 2., 2.]])

In [4]:
b = torch.eig(a)
b

torch.return_types.eig(
eigenvalues=tensor([[1.1921e-07, 0.0000e+00],
        [3.0000e+00, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [2.0000e+00, 0.0000e+00]]),
eigenvectors=tensor([]))

In [5]:
c = b.eigenvalues
c

tensor([[1.1921e-07, 0.0000e+00],
        [3.0000e+00, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [2.0000e+00, 0.0000e+00]])

In [6]:
import numpy
d = c.numpy()
e = [round(i[0]) for i in d]
e

[0.0, 3.0, 1.0, 2.0]

In [7]:
numpy.sort(e)

array([0., 1., 2., 3.], dtype=float32)