In [1]:
import torch

torch.manual_seed(7)

A = torch.randn(4,4)
b = torch.randn(4,1)

x = torch.mm(torch.inverse(A), b)
x

tensor([[ 1.9091],
        [-1.3145],
        [ 1.9841],
        [-0.3172]])

Checking for value of b:

In [2]:
b

tensor([[ 0.1382],
        [-1.6822],
        [ 0.3177],
        [ 0.1328]])

In [3]:
torch.mm(A,x)

tensor([[ 0.1382],
        [-1.6822],
        [ 0.3177],
        [ 0.1328]])