In [1]:
import torch

In [2]:
v = torch.Tensor([[3,1],[2,4]])

In [3]:
a = v.view(2,2)

In [4]:
a

tensor([[3., 1.],
        [2., 4.]])

In [5]:
b = torch.eig(a, True)

In [6]:
b

torch.return_types.eig(
eigenvalues=tensor([[2., 0.],
        [5., 0.]]),
eigenvectors=tensor([[-0.7071, -0.4472],
        [ 0.7071, -0.8944]]))

In [7]:
c = b.eigenvectors

In [8]:
c

tensor([[-0.7071, -0.4472],
        [ 0.7071, -0.8944]])

In [9]:
c.numpy()

array([[-0.70710677, -0.4472136 ],
       [ 0.70710677, -0.89442724]], dtype=float32)

In [10]:
import numpy
d = c.numpy()
e = [i[1] for i in d]
e

[-0.4472136, -0.89442724]

In [11]:
f = e/max(e)

In [12]:
g = [round(i) for i in f]

In [13]:
g

[1.0, 2.0]